EXTENSION = vestrace_safety_verify
MODULE_big = vestrace_safety_verify
OBJS = vestrace_safety_verify.o
DATA = vestrace_safety_verify--1.0.sql
PG_CONFIG = pg_config
SHLIB_LINK = -lsodium
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
