use super::{
    Requirement, RequirementFamily, RequirementId, RequirementLevel as L, VerificationClass as V,
};

pub static REQUIREMENTS: &[Requirement] = &[
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 1),
        level: L::Must,
        class: V::Static,
        spec_statement: "Vestrace должен различать authoritative/canonical state и derived state.",
        statement: "Vestrace must distinguish authoritative/canonical state from derived state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 2),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Derived state должен иметь rebuild path из более авторитетного слоя.",
        statement: "Derived state must have a rebuild path from a more authoritative layer.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 3),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "Derived state не может автоматически переписывать более авторитетный state только ради устранения drift.",
        statement: "Derived state must not automatically rewrite more authoritative state to eliminate drift.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 4),
        level: L::Must,
        class: V::Static,
        spec_statement: "Repair, recovery, governance и external-effect workflows должны использовать единый execution/policy/audit boundary.",
        statement: "Repair, recovery, governance and external-effect workflows must use a single execution/policy/audit boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 5),
        level: L::MustNot,
        class: V::Static,
        spec_statement: "Архитектура не должна вводить второй event store или параллельный orchestration runtime без отдельного ADR.",
        statement: "The architecture must not introduce a second event store or parallel orchestration runtime without a dedicated ADR.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 6),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Исправления history должны сохранять факт исходного состояния/события.",
        statement: "History corrections must preserve the fact of the original state/event.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 7),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Неопределённость должна иметь явное state representation и не сводиться автоматически к success/failure.",
        statement: "Uncertainty must have explicit state representation and not collapse to success/failure automatically.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 8),
        level: L::Must,
        class: V::Static,
        spec_statement: "Identity/reference/hash/URI не должны сами по себе предоставлять authorization.",
        statement: "Identity/reference/hash/URI must not by themselves confer authorization.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 9),
        level: L::Should,
        class: V::Static,
        spec_statement: "Новые durable entities должны иметь typed IDs и явного authority owner.",
        statement: "New durable entities must have typed IDs and an explicit authority owner.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Arc, 10),
        level: L::Must,
        class: V::Static,
        spec_statement: "Любая новая projection должна быть обозначена как projection и не становиться source of truth по умолчанию.",
        statement: "Any new projection must be labelled as projection and not become source of truth by default.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 1),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`Memory` имеет стабильную identity, а semantic content хранится в immutable revisions.",
        statement: "Memory has stable identity; semantic content lives in immutable revisions.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 2),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Изменение semantic content создаёт новую `MemoryRevision`; in-place overwrite запрещён.",
        statement: "Changing semantic content creates a new MemoryRevision; in-place overwrite is forbidden.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 3),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Active revision должна принадлежать той же Memory.",
        statement: "Active revision must belong to the same Memory.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 4),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Revision numbers должны быть монотонны и неизменяемы внутри Memory.",
        statement: "Revision numbers must be monotonic and immutable within a Memory.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 5),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Active Memory должна иметь как минимум один admissible evidence/source reference.",
        statement: "Active Memory must have at least one admissible evidence/source reference.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 6),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Derived Memory должна иметь Derivation.",
        statement: "Derived Memory must have a Derivation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 7),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "`Superseded`, `Expired`, `Rejected` и `Deleted` не должны молча возвращаться в `Active`.",
        statement: "Superseded, Expired, Rejected and Deleted must not silently return to Active.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 8),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`valid_until`, если задан, не может быть раньше `valid_from`.",
        statement: "valid_until, if set, must not be earlier than valid_from.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 9),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Confidence/importance должны быть finite и находиться в диапазоне `[0,1]`.",
        statement: "Confidence/importance must be finite and in range [0,1].",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 10),
        level: L::Must,
        class: V::Static,
        spec_statement: "Structured payload должен иметь schema identity/version.",
        statement: "Structured payload must have schema identity/version.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 11),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Scope relation не может расширить workspace authority boundary.",
        statement: "Scope relation must not extend workspace authority boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 12),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Derived canonical cognition должна иметь provenance closure до source evidence либо явной human-authored authority.",
        statement: "Derived canonical cognition must have provenance closure to source evidence or explicit human-authored authority.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 13),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`Claim` и `Memory` должны оставаться различимыми domain concepts.",
        statement: "Claim and Memory must remain distinguishable domain concepts.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 14),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Claim status `Supported` не должен трактоваться как абсолютная внешняя истина.",
        statement: "Claim status Supported must not be treated as absolute external truth.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 15),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Claim, потерявший всё admissible supporting evidence, должен перейти через revalidation.",
        statement: "Claim losing all admissible supporting evidence must go through revalidation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 16),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Open semantic conflict должен оставаться явным до reconciliation.",
        statement: "Open semantic conflict must remain explicit until reconciliation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 17),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "Conflict не должен автоматически разрешаться универсальным `latest timestamp wins`.",
        statement: "Conflict must not be auto-resolved by universal latest-timestamp-wins.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 18),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Conflict resolution должен сохранять basis/evidence/policy/human decision.",
        statement: "Conflict resolution must preserve basis/evidence/policy/human decision.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 19),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Supersession не должен удалять superseded history.",
        statement: "Supersession must not delete superseded history.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mem, 20),
        level: L::Should,
        class: V::Static,
        spec_statement: "Cognitive assets (agents/skills/workflows) должны быть отдельными versioned assets, а не Memory records.",
        statement: "Cognitive assets (agents/skills/workflows) must be separate versioned assets, not Memory records.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 1),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`recorded_at` и `occurred_at` должны иметь различимую семантику.",
        statement: "recorded_at and occurred_at must have distinguishable semantics.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 2),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Unknown `occurred_at` не должен блокировать authoritative recording, если `recorded_at` известен.",
        statement: "Unknown occurred_at must not block authoritative recording if recorded_at is known.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 3),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Knowledge validity (`valid_from/to`) должна быть независима от recording time.",
        statement: "Knowledge validity (valid_from/to) must be independent of recording time.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 4),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Current retrieval не должен выдавать superseded/expired knowledge как current.",
        statement: "Current retrieval must not return superseded/expired knowledge as current.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 5),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "`as_of` query должна использовать соответствующую historical state semantics, а не current projection.",
        statement: "as_of query must use historical state semantics, not current projection.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 6),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Canonical mutation должна иметь expected version/revision precondition, когда возможна конкуренция.",
        statement: "Canonical mutation must have expected version/revision precondition when competition is possible.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 7),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Version mismatch должен давать conflict/stale result без silent overwrite.",
        statement: "Version mismatch must yield conflict/stale result without silent overwrite.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 8),
        level: L::MustNot,
        class: V::Domain,
        spec_statement: "Wall-clock timestamp не должен использоваться как доказательство глобального causal order без дополнительного ordering contract.",
        statement: "Wall-clock timestamp must not be used as proof of global causal order without additional ordering contract.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 9),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Lease/heartbeat не должен сам по себе повышать authority или менять logical revision.",
        statement: "Lease/heartbeat must not by itself elevate authority or change logical revision.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Tmp, 10),
        level: L::Should,
        class: V::Stateful,
        spec_statement: "Canonical append-only streams должны иметь проверяемый monotonic order внутри aggregate/scope.",
        statement: "Canonical append-only streams must have verifiable monotonic order within aggregate/scope.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 1),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Значимая cognitive mutation должна сохранять actor, target, expected state, reason/intent и resulting revision/fact.",
        statement: "Significant cognitive mutation must preserve actor, target, expected state, reason/intent and resulting revision/fact.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 2),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "Correction не должна переписывать старую revision.",
        statement: "Correction must not rewrite old revision.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 3),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Deterministic reconciliation должен использовать более авторитетный source/state.",
        statement: "Deterministic reconciliation must use a more authoritative source/state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 4),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Semantic ambiguity не должна маскироваться под deterministic repair.",
        statement: "Semantic ambiguity must not be masked as deterministic repair.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 5),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Policy-guided reconciliation должна ссылаться на exact policy version.",
        statement: "Reconciliation must produce a reconciliation record preserving inputs and outcome.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 6),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Human-required reconciliation не должна исполняться автоматически.",
        statement: "Reconciliation record must be auditable and replayable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 7),
        level: L::Must,
        class: V::Static,
        spec_statement: "State Engine не должен вводить generic Task/Action aggregates, дублирующие существующих владельцев execution semantics.",
        statement: "Compensation must be a new effect, not a retroactive erase.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Mut, 8),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Reconciliation result должен сохранять evidence/basis и relation к conflicting inputs.",
        statement: "Reconciliation must not silently amplify authority beyond the reconciling source.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 1),
        level: L::Must,
        class: V::Security,
        spec_statement: "Security/workspace/classification/share filters должны применяться до disclosure запрещённого content downstream ranking/model stages.",
        statement: "Retrieval must return exact revision content, not a mutable current snapshot, when a revision is requested.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 2),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Current retrieval должен исключать superseded/expired cognition как current truth.",
        statement: "Retrieval must hydrate the exact referenced revision payload, not silently substitute the latest.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 3),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Unresolved conflicts должны возвращаться явно, а не превращаться в выбранный факт без reconciliation.",
        statement: "Retrieval authorization must be checked at hydration time, not only at index time.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 4),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`ContextPack.used_budget` не должен превышать hard token/content budget.",
        statement: "Retrieval must not return content from a workspace the caller is not authorized for.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 5),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Каждый ContextPack item должен сохранять source/revision provenance reference.",
        statement: "ContextPack must include provenance/revision metadata for each included item.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 6),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Каждый ContextPack item должен иметь inclusion explanation достаточную для диагностики.",
        statement: "ContextPack must distinguish Full, Summary, Atomic and Reference representations.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 7),
        level: L::Must,
        class: V::Security,
        spec_statement: "ContextPack должен соблюдать classification/model-destination policy.",
        statement: "ContextPack must enforce a token budget and not silently exceed it.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 8),
        level: L::MustNot,
        class: V::Domain,
        spec_statement: "Включение item в ContextPack не должно повышать его semantic authority.",
        statement: "Retrieval must not present superseded or expired content as current without explicit temporal annotation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 9),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Failure derived retrieval channel должен приводить к explicit degraded mode, если безопасный fallback существует.",
        statement: "Multi-channel retrieval must fuse results with a deterministic and auditable strategy.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 10),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Если безопасного fallback нет, retrieval должен fail closed.",
        statement: "Channel degradation must be observable and must not silently substitute results.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 11),
        level: L::Should,
        class: V::Domain,
        spec_statement: "Несопоставимые channel scores следует объединять rank-based fusion, а не прямым суммированием.",
        statement: "Retrieval invalidation must propagate when source content is superseded or corrected.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 12),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Cache/context generation должен инвалидироваться при релевантном canonical/policy/share/classification change.",
        statement: "Retrieval should support temporal as_of queries using historical revision state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 13),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Representation levels `Full/Summary/Atomic/Reference` должны сохранять ссылку на original source/revision.",
        statement: "Retrieval journal must record the intent, parameters, channels and resulting pack.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 14),
        level: L::Must,
        class: V::Security,
        spec_statement: "Cross-workspace mounted content должен проходить source и target policy checks при каждом governed access.",
        statement: "Retrieval must not silently inject content from a different workspace.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ret, 15),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Retrieval run должен быть journalable с policy/version/degradation metadata.",
        statement: "Retrieval must enforce sensitivity/classification filters at the hydration boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 1),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Feedback signal должен ссылаться на exact execution/model/tool/policy revisions.",
        statement: "Feedback signals must reference exact execution, model, tool and policy revisions.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 2),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Raw evaluation facts должны храниться отдельно от learned projections/recommendations.",
        statement: "Raw evaluation facts must be stored separately from learned projections and recommendations.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 3),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Learning pipeline не должен автоматически повышать capabilities/permissions.",
        statement: "The learning pipeline must not automatically elevate capabilities or permissions.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 4),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Learning pipeline не должен обходить governance policy при изменении agents/skills/workflows.",
        statement: "The learning pipeline must not bypass governance policy when changing agents, skills or workflows.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 5),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Изменение cognitive assets по результатам learning должно быть versioned/provenanced.",
        statement: "Learning-driven cognitive asset changes must be versioned and provenanced.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 6),
        level: L::Should,
        class: V::Domain,
        spec_statement: "Deterministic/human signals должны иметь более высокий default authority, чем model-judge heuristic signals.",
        statement: "Deterministic and human signals should have higher default authority than model-judge heuristic signals.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 7),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Learned performance conclusion должен сохранять ссылки на underlying measurements.",
        statement: "Learned performance conclusions must retain references to underlying measurements.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Lrn, 8),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Удаление learned projection не должно уничтожать raw execution/evaluation history.",
        statement: "Deleting a learned projection must not destroy raw execution or evaluation history.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 1),
        level: L::Must,
        class: V::Security,
        spec_statement: "Runtime authorization определяется effective capability/policy, а не role name.",
        statement: "Capability must be a durable, constrained grant, not a coarse enum.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 2),
        level: L::Must,
        class: V::Security,
        spec_statement: "Default policy — deny.",
        statement: "CapabilityGrant must specify resource scope, actions, constraints and expiry.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 3),
        level: L::Must,
        class: V::Static,
        spec_statement: "Capability должна поддерживать restriction по operation/tool, resource/scope, validity, budget, risk и conditions.",
        statement: "Delegation must attenuate capabilities; it must not amplify them.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 4),
        level: L::Must,
        class: V::Security,
        spec_statement: "Expired capability должна быть rejected.",
        statement: "PolicyDecision must be the single authorization verdict for every guarded action.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 5),
        level: L::Must,
        class: V::Security,
        spec_statement: "Child/subagent effective authority не может быть шире parent effective authority.",
        statement: "Every entry point (HTTP, MCP, worker, internal) must pass through the authorization boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 6),
        level: L::Must,
        class: V::Security,
        spec_statement: "Delegation требует явного delegation permission/contract.",
        statement: "Authorization bypass must be impossible without an explicit policy grant.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 7),
        level: L::Must,
        class: V::Security,
        spec_statement: "Delegation depth должна быть bounded.",
        statement: "Risk assessment must be part of the policy decision when applicable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 8),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Risk categories как минимум `low/medium/high/critical`.",
        statement: "Budget consumption must be checked at effect time, not only at planning time.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 9),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Context может повысить effective risk.",
        statement: "Hierarchical budgets must attenuate downstream, not amplify.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 10),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Approval не должен преодолевать explicit deny, hard budget или capability ceiling.",
        statement: "Capability revocation must take effect without requiring a new grant cycle.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 11),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Policy decision должен сохранять exact policy version и relevant input state.",
        statement: "Connected endpoints may only preserve or reduce delegated authority, never amplify it.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 12),
        level: L::Must,
        class: V::Security,
        spec_statement: "Material change approved operation/intent должен инвалидировать approval.",
        statement: "Effective authority is the intersection of Brain capability/policy, Face-local policy and host/organ OS rights.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 13),
        level: L::Should,
        class: V::Evidence,
        spec_statement: "Budget reservations/accounting должны быть auditable.",
        statement: "Policy decisions must be auditable with actor, action, resource, decision and basis.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Cap, 14),
        level: L::Must,
        class: V::Security,
        spec_statement: "Agent-facing API не должен предоставлять self-escalation capability.",
        statement: "Stale capability cache must not grant authority after revocation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 1),
        level: L::Must,
        class: V::Security,
        spec_statement: "Workspace является authority/isolation boundary.",
        statement: "Workspace isolation must prevent cross-workspace data leakage.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 2),
        level: L::Must,
        class: V::Security,
        spec_statement: "Workspace-local `global` не должен означать cross-workspace global.",
        statement: "Cross-workspace sharing must be a two-sided grant + mount, not a one-sided grant.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 3),
        level: L::Must,
        class: V::Security,
        spec_statement: "Actor identity и authority должны проверяться независимо.",
        statement: "MemoryMount must reference an exact source revision, not a mutable latest.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 4),
        level: L::Must,
        class: V::Security,
        spec_statement: "Cross-workspace Memory access требует explicit source grant и target acceptance.",
        statement: "Grant revocation must propagate to mounts and invalidate derived projections.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 5),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Wildcard target grants запрещены.",
        statement: "Stale mount must not serve content after grant revocation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 6),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Mounted memory не может быть автоматически re-shared третьему workspace.",
        statement: "Federation trust must not imply local permission.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 7),
        level: L::Must,
        class: V::Security,
        spec_statement: "Source и target policy должны проверяться независимо.",
        statement: "Remote identity must be validated against federation trust policy, not assumed.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 8),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Revoked/expired/stale mount не должен выдавать content.",
        statement: "Federated data must not bypass local classification/sensitivity governance.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 9),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`SharedMemoryRef` должен быть namespaced source workspace + exact memory/revision/grant context.",
        statement: "Grant lifecycle must be explicit: created, accepted, revoked, expired.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 10),
        level: L::MustNot,
        class: V::Domain,
        spec_statement: "SharedMemoryRef не должен подставляться как local MemoryId.",
        statement: "Grant and mount operations must be auditable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 11),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Local derivation/import from mounted content должен сохранять source provenance.",
        statement: "Cross-workspace sharing must not create a second authority owner for the shared Memory.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 12),
        level: L::Must,
        class: V::Security,
        spec_statement: "Federation trust/identity recognition не должен сам по себе разрешать data disclosure.",
        statement: "Sharing should support partial scope (subset of revisions, filtered content).",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 13),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Revocation не должна переписывать исторический факт уже совершённого disclosure.",
        statement: "Remote endpoint must not gain authority beyond what the local grant explicitly permits.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Idw, 14),
        level: L::Must,
        class: V::Security,
        spec_statement: "Cross-workspace access не должен требовать снятия RLS/normal workspace isolation.",
        statement: "Federation disconnect must not silently imply effect success or restored trust.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 1),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "HealthFinding должен содержать invariant, scope, evidence, severity и repairability.",
        statement: "Health findings must be produced by an invariant registry, not ad-hoc checks.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 2),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Aggregate health является projection, а не canonical truth.",
        statement: "InvariantDefinition must specify the invariant, the check and the expected healthy state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 3),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`UNKNOWN` health не должен трактоваться как `HEALTHY`.",
        statement: "HealthFinding must reference the invariant, the observed state and the severity.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 4),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Severity и repair risk должны быть отдельными dimensions.",
        statement: "RepairPlan must be derived from findings, not directly from ad-hoc rebuild requests.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 5),
        level: L::Must,
        class: V::Static,
        spec_statement: "Invariant definition должен иметь stable ID и version.",
        statement: "RepairExecution must go through the authorization boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 6),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Deterministic auto-repair разрешён только из более авторитетного source/state.",
        statement: "Repair verification must re-check invariants after execution.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 7),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "Checker не должен напрямую выполнять hidden mutation.",
        statement: "Repair must only auto-modify state deterministically reconstructible from a more authoritative layer.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 8),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Repair должен проходить immutable RepairPlan до execution.",
        statement: "Recurrence detection must identify repeated findings on the same invariant.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 9),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "RepairPlan с stale preconditions должен получить `STALE_PLAN` и не исполняться.",
        statement: "Flapping detection must identify oscillating repair/relapse cycles.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 10),
        level: L::Must,
        class: V::Security,
        spec_statement: "Repair execution должен проходить capability/policy gates согласно risk/repairability.",
        statement: "Disposition must classify finding as auto-repairable, manual-required or accepted-risk.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 11),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "`RepairExecution=SUCCEEDED` не должен автоматически закрывать finding.",
        statement: "Repair budget must limit repair actions within a window.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 12),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Finding `RESOLVED` требует successful verification evidence.",
        statement: "Doctor must separate inspection, plan and repair phases.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 13),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Verification failure должен оставить finding open/reopened.",
        statement: "Repair must produce an auditable execution record.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 14),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Occurrences одного logical finding должны сохраняться отдельно от finding identity.",
        statement: "Repair must not silently delete canonical history.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 15),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Auto-repair должен иметь retry/attempt budget и cooldown.",
        statement: "Health finding must not be silenced without an explicit disposition.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 16),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Flapping должен прекращать бесконечный auto-repair loop.",
        statement: "Repair should support dry-run mode showing planned actions without execution.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 17),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Health propagation должна следовать declared dependencies, а не глобальному worst-state rule.",
        statement: "Invariant registry must be extensible without modifying the repair execution engine.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 18),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Suppression/AcceptedRisk должны иметь actor, reason, expiry/policy и audit.",
        statement: "Health check must record the invariant version, timestamp and observed state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 19),
        level: L::MustNot,
        class: V::Domain,
        spec_statement: "Suppression не должен удалять finding или превращать raw integrity в healthy.",
        statement: "Repair verification failure must escalate, not silently retry.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Hlt, 20),
        level: L::Should,
        class: V::Stateful,
        spec_statement: "Repair steps должны быть idempotent/restartable там, где это технически возможно.",
        statement: "Accepted-risk disposition must be explicit and revocable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 1),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Immutable ExternalEffectIntent должен быть сохранён до external dispatch.",
        statement: "External effect must start from an explicit ExternalEffectIntent.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 2),
        level: L::Must,
        class: V::Security,
        spec_statement: "Effect должен пройти capability/policy/budget authorization до dispatch.",
        statement: "Effect adapter must conform to a typed contract: prepare, commit, verify.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 3),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Adapter должен объявлять delivery semantics: at-most-once/at-least-once/effectively-once/unknown.",
        statement: "Effect dispatch must produce a receipt with status and correlation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 4),
        level: L::MustNot,
        class: V::Static,
        spec_statement: "Adapter/runtime не должен заявлять universal exactly-once без доказуемого provider contract.",
        statement: "UNKNOWN effect status must be first-class, not collapsed to success or failure.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 5),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Idempotency/retry safety должна быть adapter contract, а не свободное решение агента.",
        statement: "Effect idempotency must prevent duplicate external side-effects on retry.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 6),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Transport timeout не должен автоматически означать, что effect не произошёл.",
        statement: "Delivery confirmation must not be inferred from dispatch success.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 7),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "`UNKNOWN` outcome должен быть first-class state.",
        statement: "Reconciliation must compare intent, receipt and observed state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 8),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "UNKNOWN external effect не должен автоматически переводиться в FAILED.",
        statement: "Compensation must be a new effect, not a retroactive erase.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 9),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "UNKNOWN effect не должен автоматически retry, если adapter не доказал retry-safe semantics.",
        statement: "Reversibility must be declared per effect kind, not assumed.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 10),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Reconciliation должен использовать strongest available read-back/evidence mechanism.",
        statement: "Effect timeout must not silently imply success or failure.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 11),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`REVERSIBLE`, `COMPENSATABLE`, `IRREVERSIBLE`, `UNKNOWN_REVERSIBILITY` должны быть различимы.",
        statement: "Effect authority must be checked at dispatch time and at commit time.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 12),
        level: L::MustNot,
        class: V::Domain,
        spec_statement: "Compensation не должна называться rollback.",
        statement: "Effect lifecycle must be auditable: intent, dispatch, receipt, reconciliation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 13),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Compensation должна ссылаться на compensated effect.",
        statement: "Organ or host output is observation/evidence before it may become durable cognition.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 14),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Critical external preconditions должны проверяться непосредственно перед dispatch.",
        statement: "Reconnect/restart/recreate must not silently imply effect success or restored trust.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 15),
        level: L::Must,
        class: V::Security,
        spec_statement: "Material mutation approved intent требует новой authorization.",
        statement: "Effect adapter must declare capability contract (what it can and cannot do).",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 16),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Dispatched effect должен иметь receipt/evidence record.",
        statement: "Effect queue must preserve order within a run and must not silently drop effects.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 17),
        level: L::MustNot,
        class: V::Evidence,
        spec_statement: "Receipt/ACK не должен автоматически считаться desired business outcome.",
        statement: "Effect must not bypass the single execution/policy/audit boundary.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Ext, 18),
        level: L::Must,
        class: V::Security,
        spec_statement: "Secret material не должен сохраняться в effect traces/receipts в plaintext.",
        statement: "Adapter qualification must include fault suite evidence.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 1),
        level: L::Must,
        class: V::Domain,
        spec_statement: "HealthFinding и Incident должны быть разными concepts.",
        statement: "Incident must be created when a significant failure or trust violation is detected.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 2),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Incident lifecycle должен включать containment до trust restoration.",
        statement: "Incident must have a containment action that limits damage.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 3),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Process restart не должен автоматически возвращать scope в TRUSTED.",
        statement: "TrustState must be explicit and must not silently recover.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 4),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Startup recovery должен классифицировать unfinished work, а не resume-all.",
        statement: "Recovery does not restore trust without revalidation evidence.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 5),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Ambiguous external dispatch после crash должен переходить в UNKNOWN/reconciliation path.",
        statement: "RevalidationRun must be a typed run with explicit success/failure criteria.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 6),
        level: L::MustNot,
        class: V::Recovery,
        spec_statement: "Ambiguous irreversible effect не должен автоматически повторяться после restart.",
        statement: "Recovery classification must distinguish transient, partial, permanent failure.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 7),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Recovery point должен ссылаться на доказанно согласованное state/scope position.",
        statement: "Incident must preserve the evidence that triggered it.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 8),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Snapshot должен проходить integrity/schema/continuity validation до использования как recovery source.",
        statement: "Incident must not be silently closed without disposition.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 9),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Derived state после restore должен rebuild/revalidate из canonical state.",
        statement: "Trust degradation must be proportional to evidence severity.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 10),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`AVAILABLE`, `HEALTHY`, `TRUSTED`, `RECOVERED`, `REVALIDATED` должны оставаться различимыми.",
        statement: "Checkpoint restoration must validate against canonical event history.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 11),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Trust не может перейти `UNTRUSTED → TRUSTED` без successful required RevalidationRun.",
        statement: "Revalidation must test the original invariant, not a proxy.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 12),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "RevalidationRun должен сохранять scope, level, checks, evidence и result.",
        statement: "Incident closure must record disposition, evidence and authority.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 13),
        level: L::Must,
        class: V::Domain,
        spec_statement: "`INCONCLUSIVE` revalidation должен быть допустимым результатом и не считаться PASSED.",
        statement: "Concurrent incidents on the same resource must be correlated.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 14),
        level: L::MustNot,
        class: V::Recovery,
        spec_statement: "Divergent histories не должны автоматически merge через `latest wins`.",
        statement: "Recovery must not silently amplify authority beyond pre-incident state.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 15),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Recovery automation должен иметь bounded retry/budget и обнаруживать recovery loops.",
        statement: "Revalidation failure must escalate, not silently retry.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 16),
        level: L::Should,
        class: V::Evidence,
        spec_statement: "Перед destructive recovery следует сохранять forensic evidence.",
        statement: "Incident must not be auto-closed by time alone.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 17),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Capability restoration после trust incident должна следовать policy и MAY быть progressive.",
        statement: "Recovery should support partial revalidation for multi-component systems.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Rec, 18),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Recovery не должен переписывать history так, будто failure/incident не происходил.",
        statement: "Recovery record must be auditable and replayable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 1),
        level: L::Must,
        class: V::Static,
        spec_statement: "Crypto controls и DataPolicy controls должны быть независимыми gates.",
        statement: "Secrets must not be stored as ordinary Memory.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 2),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Base sensitivity ordering: PUBLIC < INTERNAL < CONFIDENTIAL < RESTRICTED.",
        statement: "SecretRef must reference a key provider, not embed plaintext.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 3),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Derived data не должен автоматически понижать classification относительно источников.",
        statement: "DataPolicy must classify data sensitivity and enforce boundaries.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 4),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Declassification должен быть отдельным governed decision с provenance.",
        statement: "Classification lineage must track sensitivity propagation through derivations.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 5),
        level: L::MustNot,
        class: V::Security,
        spec_statement: "Secret plaintext не должен храниться как ordinary Memory.",
        statement: "Model boundary must prevent classified data from leaking to unauthorized models.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 6),
        level: L::Must,
        class: V::Security,
        spec_statement: "Durable secret usage должен использовать opaque SecretRef + controlled resolver/backend.",
        statement: "Retention policy must be enforced and must not be bypassed by ad-hoc deletion.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 7),
        level: L::Should,
        class: V::Security,
        spec_statement: "Large/CAS data at rest следует защищать envelope encryption при включённом crypto profile.",
        statement: "Legal hold must suspend retention deletion.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 8),
        level: L::Must,
        class: V::Static,
        spec_statement: "Crypto metadata должна поддерживать algorithm/version agility.",
        statement: "Deletion must verify dependency-aware cleanup (no orphaned references).",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 9),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Hash integrity и signature/authorship должны быть различимыми guarantees.",
        statement: "Deletion verification must produce auditable evidence.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 10),
        level: L::Should,
        class: V::Evidence,
        spec_statement: "Critical audit history должна поддерживать tamper-evident chaining/checkpoints в TRUSTED profile.",
        statement: "Export must be governed by DataPolicy and must not bypass classification.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 11),
        level: L::Must,
        class: V::Security,
        spec_statement: "Capability grant не должен обходить DataPolicy restriction.",
        statement: "Export must produce integrity-verifiable artifacts (signed).",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 12),
        level: L::Must,
        class: V::Security,
        spec_statement: "DataPolicy allow не должен обходить отсутствие required capability.",
        statement: "Audit log must be tamper-evident and must not be silently modifiable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 13),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Retention lifecycle должен различать ACTIVE/EXPIRED/PENDING_DISPOSAL/DISPOSED.",
        statement: "Key lifecycle must have explicit rotation and revocation.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 14),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "DataHold должен иметь scope, authority и reason.",
        statement: "Key revocation must invalidate encrypted data without requiring full re-encryption.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 15),
        level: L::Must,
        class: V::Domain,
        spec_statement: "Logical delete, physical delete и crypto erasure должны быть различимы.",
        statement: "DataPolicy must apply to federated data, not only local data.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 16),
        level: L::MustNot,
        class: V::Evidence,
        spec_statement: "Delete result не должен заявлять уничтожение backup copies, если оно не доказано.",
        statement: "Policy enforcement must be auditable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 17),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Evidence deletion должен инициировать revalidation зависимых claims/derived state.",
        statement: "WorkspaceKek must protect workspace-local encryption keys.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 18),
        level: L::Must,
        class: V::Security,
        spec_statement: "Export должен быть governed operation с exact scope/recipient/purpose/classification.",
        statement: "Cross-workspace data access must enforce both source and target governance policies.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 19),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Export bundle должен иметь manifest/provenance/integrity metadata.",
        statement: "Redaction must preserve semantic utility while protecting sensitive content.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 20),
        level: L::Must,
        class: V::Security,
        spec_statement: "Federation identity/trust не должен сам по себе разрешать classified data transfer.",
        statement: "Governance actions must be auditable with actor, action, resource and decision.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 21),
        level: L::Must,
        class: V::Security,
        spec_statement: "Model invocation должен проверять destination/locality/classification/redaction policy.",
        statement: "Retention expiry must not silently delete data under legal hold.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 22),
        level: L::Must,
        class: V::Security,
        spec_statement: "RESTRICTED data не должен отправляться provider, запрещённому DataPolicy.",
        statement: "Export must support filtered scope (subset of data).",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 23),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "Signature/hash/audit-chain/key-compromise anomaly должна влиять на trust и запускать соответствующий incident/revalidation path.",
        statement: "Sensitive data must not appear in logs or audit trails without redaction.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 24),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Governance decision должен ссылаться на exact policy version.",
        statement: "Data classification must be immutable once applied to a revision.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 25),
        level: L::MustNot,
        class: V::Stateful,
        spec_statement: "Новая policy version не должна ретроактивно переписывать историю предыдущего решения.",
        statement: "Key rotation should be automated with zero downtime.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Gov, 26),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Deletion считается завершённым только после DeletionVerification согласно заявленной deletion semantics.",
        statement: "Governance policy changes must be versioned and auditable.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 1),
        level: L::Must,
        class: V::Static,
        spec_statement: "Tests, conformance и qualification должны быть отдельными concepts.",
        statement: "Qualification profiles must be defined with explicit requirement sets.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 2),
        level: L::Must,
        class: V::Static,
        spec_statement: "Каждый MUST requirement в заявляемом profile должен иметь verification path.",
        statement: "Each requirement in a profile must have at least one conformance case.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 3),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "Qualification result должен сохранять build/source/config/environment identity.",
        statement: "Conformance case must map to one or more requirement IDs.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 4),
        level: L::Must,
        class: V::Static,
        spec_statement: "Profiles должны иметь dependency closure.",
        statement: "Conformance result must be machine-readable with pass/fail/skip and evidence.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 5),
        level: L::Must,
        class: V::Static,
        spec_statement: "Installation capability manifest должен явно указывать limitations для заявляемого profile.",
        statement: "Profile dependency chain must be enforced: later profiles require earlier.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 6),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Skipped обязательный MUST requirement должен приводить к profile qualification failure.",
        statement: "QualificationBundle must contain all conformance results for a profile.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 7),
        level: L::Must,
        class: V::Security,
        spec_statement: "Security/governance hard gate failure не может компенсироваться высоким quality score.",
        statement: "QualificationBundle must contain environment and build identity.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 8),
        level: L::Must,
        class: V::Fault,
        spec_statement: "AUTONOMY/TRUSTED qualification должна включать deterministic crash/fault scenarios.",
        statement: "Fault suite must provide deterministic fault injection for RECOVERY/FAULT class requirements.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 9),
        level: L::Must,
        class: V::Recovery,
        spec_statement: "TRUSTED qualification должна включать recovery + revalidation scenarios.",
        statement: "Golden scenario suites must cover end-to-end product scenarios.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 10),
        level: L::Should,
        class: V::Stateful,
        spec_statement: "Cognitive qualification должна проверять properties/evidence, а не exact LLM wording.",
        statement: "Qualification evidence must be reproducible.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 11),
        level: L::Must,
        class: V::Interop,
        spec_statement: "Adapter/backend qualification должна проверять заявленные idempotency/recovery/security semantics.",
        statement: "Requirement IDs must be stable across documentation versions.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 12),
        level: L::Must,
        class: V::Interop,
        spec_statement: "Unsupported compatibility должна быть explicit, а не silent best-effort.",
        statement: "TRUSTED profile must require closure of all MUST-level requirements.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 13),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "QualificationBundle должен содержать suite version и per-requirement evidence/results.",
        statement: "Profile upgrade must not silently inherit unverified requirements.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 14),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Material environment/provider/backend/policy/crypto/schema change должен уметь инвалидировать/stale qualification baseline.",
        statement: "Qualification should support partial profile assessment for incremental progress.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 15),
        level: L::Must,
        class: V::Stateful,
        spec_statement: "Qualification не является бессрочным сертификатом продукта.",
        statement: "Conformance case must record the invariant version it was validated against.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 16),
        level: L::Must,
        class: V::Security,
        spec_statement: "Destructive qualification scenarios не должны выполняться против production workspace без специального isolated qualification contract.",
        statement: "Qualification baseline must be versioned and immutable once published.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 17),
        level: L::Must,
        class: V::Interop,
        spec_statement: "Federation participant self-asserted `TRUSTED` status не должен приниматься как достаточное доказательство trust.",
        statement: "Milestone labels must not imply named profile qualification without evidence closure.",
    },
    Requirement {
        id: RequirementId::new(RequirementFamily::Qual, 18),
        level: L::Must,
        class: V::Evidence,
        spec_statement: "v1.0 Trust claim требует успешного TRUSTED profile и опубликованных known limitations.",
        statement: "Qualification gate must block release if any MUST-level requirement fails.",
    },
];

pub fn all() -> &'static [Requirement] {
    REQUIREMENTS
}

pub fn find(id: &RequirementId) -> Option<&'static Requirement> {
    REQUIREMENTS.iter().find(|r| &r.id == id)
}

pub fn by_family(family: RequirementFamily) -> impl Iterator<Item = &'static Requirement> {
    REQUIREMENTS.iter().filter(move |r| r.id.family == family)
}

pub fn count() -> usize {
    REQUIREMENTS.len()
}
