use std::sync::Arc;

use anyhow::{Context, anyhow};
use secrecy::ExposeSecret;
use vestrace_application::{
    EffectiveRequestLimits, HealthInspectionService, InspectedFinding, InvariantObserver,
    RequestContext,
    embedding::{EmbeddingLegacyAdoptionService, StartLegacyAdoption},
    standard_invariants,
};
use vestrace_domain::{PrincipalId, WorkspaceId, id::LegacyAdoptionId};
use vestrace_infrastructure::crypto::ContentMaterialCodec;
use vestrace_infrastructure::postgres::{
    PgEmbeddingJobRepository, PgEmbeddingLegacyAdoptionRepository, PgGovernedContentMaterializer,
    PgGovernedEmbeddingJobFactory, PgModelRequestEvidenceRepository,
};
use vestrace_infrastructure::{AppConfig, PgInvariantObserver, PgStore};

#[derive(clap::ValueEnum, Clone, Debug)]
pub enum RebuildTarget {
    SearchDocuments,
    Embeddings,
    All,
}

pub async fn run(config: &AppConfig, target: &RebuildTarget) -> anyhow::Result<()> {
    let url = config.database.url.expose_secret();
    let redacted = crate::commands::redact_url(url);

    print!("Connecting to database at {redacted} ... ");
    let store = PgStore::connect(&config.database)
        .await
        .context("database is unavailable")?;
    println!("OK");

    // This command is the remediation two diagnostics print, so it has to run.
    // It did not: the insert named `memories.content_text` and
    // `search_documents.search_tsv`, and neither column exists — a memory's
    // content lives on its active revision, and the index column is
    // `fts_vector`, generated. `vestrace rebuild search-documents` failed on
    // the first statement in every deployment.
    //
    // Scoping is per configured workspace for the same reason the doctor's is:
    // `memories` and `search_documents` are forced under row level security, so
    // an unscoped sweep sees nothing at all.
    if config.workspaces.is_empty() {
        return Err(anyhow!(
            "rebuild: no workspaces are configured; set `workspaces` so there \
             is something to rebuild"
        ));
    }

    let principal_id = PrincipalId::new();

    for workspace in &config.workspaces {
        let workspace_id = WorkspaceId::from_uuid(*workspace);
        let ctx = RequestContext::new(workspace_id, principal_id);

        match target {
            RebuildTarget::SearchDocuments | RebuildTarget::All => {
                print!("Rebuilding search documents for workspace {workspace} ... ");
                let count = rebuild_search_documents(&store, &ctx).await?;
                println!("done ({count} documents rebuilt)");
            }
            _ => {}
        }

        match target {
            RebuildTarget::Embeddings | RebuildTarget::All => {
                print!("Rebuilding embeddings for workspace {workspace} ... ");
                let count = rebuild_embeddings(config, &store, &ctx).await?;
                println!("done ({count} embeddings rebuilt)");
            }
            _ => {}
        }
    }

    println!();
    println!("Running post-rebuild verification ... ");

    let observer = Arc::new(PgInvariantObserver::new(store));
    let inspection = HealthInspectionService::new(standard_invariants());

    let mut error_count = 0usize;
    let mut warning_count = 0usize;

    for workspace in &config.workspaces {
        let ctx = RequestContext::new(WorkspaceId::from_uuid(*workspace), principal_id);
        let observations = observer
            .observe(&ctx)
            .await
            .context("post-rebuild verification failed")?;
        let findings = inspection
            .inspect(observations, vestrace_domain::time::now())
            .context("an observation could not be resolved against the registry")?;

        for entry in &findings {
            let label = if entry.is_error() { "ERROR" } else { "WARN " };
            println!(
                "[{label}] {}@{}: {}",
                entry.finding.invariant_id(),
                entry.finding.invariant_version(),
                entry.detail
            );
        }
        error_count += findings.iter().filter(|entry| entry.is_error()).count();
        warning_count += findings
            .iter()
            .filter(|entry| !InspectedFinding::is_error(entry))
            .count();
    }

    if error_count > 0 {
        Err(anyhow!("verification found errors after rebuild"))
    } else if warning_count > 0 {
        println!("Verification: warnings found, no errors");
        Ok(())
    } else {
        println!("Verification: all checks passed");
        Ok(())
    }
}

/// Rebuild the text index from each active memory's active revision.
///
/// `fts_vector` is generated by the schema, so it is deliberately not written
/// here — computing it in this command would let the rebuilt rows disagree with
/// the ones the write path produces.
async fn rebuild_search_documents(
    store: &PgStore,
    context: &RequestContext,
) -> Result<i64, anyhow::Error> {
    let mut scoped = store
        .begin_scoped(context)
        .await
        .context("workspace scope could not be established")?;

    let rows = sqlx::query(
        r#"
        INSERT INTO search_documents (id, memory_id, workspace_id, title, content, created_at, updated_at)
        SELECT
            gen_random_uuid(),
            m.id,
            m.workspace_id,
            '',
            r.content,
            r.created_at,
            r.created_at
        FROM memories m
        JOIN memory_revisions r ON r.id = m.active_revision_id
        WHERE m.workspace_id = $1 AND m.status = 'active'
        ON CONFLICT (workspace_id, memory_id) DO UPDATE SET
            content = EXCLUDED.content,
            updated_at = EXCLUDED.updated_at
        RETURNING 1
        "#,
    )
    .bind(context.workspace_id.as_uuid())
    .fetch_all(scoped.connection())
    .await?;

    scoped
        .commit()
        .await
        .context("search document rebuild could not be committed")?;

    Ok(rows.len() as i64)
}

/// Fill in the embeddings that are missing.
///
/// # Why this is a command rather than part of the write path
///
/// Producing an embedding is a network call to a model. Doing it inside the
/// transaction that writes a memory would make creating a memory fail whenever
/// the model is unreachable — trading a capability the system has for an index
/// it would like.
///
/// So the gap is filled here, and it is a *stated* gap:
/// is a registered invariant, so a workspace whose index is behind says so in
///  rather than returning quietly incomplete search results.
/// That is the lesson from , which nothing wrote for months
/// while every retrieval succeeded and returned nothing.
async fn rebuild_embeddings(
    config: &AppConfig,
    store: &PgStore,
    context: &RequestContext,
) -> Result<usize, anyhow::Error> {
    if crate::commands::server::build_embedding_provider(config, store)?.is_none() {
        // Nothing configured is not a failure. It is the deployment saying it
        // has no vector channel, which the retrieval journal also records.
        println!();
        println!(
            "  no embedding model is configured; set [embedding] enabled, base_url and              model_name to give retrieval a vector channel"
        );
        return Ok(0);
    }

    // Adoption never copies a legacy vector. It creates governed rebuild jobs
    // that recompute each one through the ordinary provider path, so this
    // command starts or resumes a durable plan and reports what the plan says
    // -- it does not embed anything itself, and the worker does the work.
    let legacy_spaces = legacy_space_registrations(store, context).await?;
    if legacy_spaces.is_empty() {
        println!();
        println!("  no legacy embedding space remains in this workspace");
        return Ok(0);
    }
    let Some(canonical) = active_canonical_registration(store, context).await? else {
        return Err(anyhow!(
            "rebuild: this workspace has {} legacy embedding space(s) but no active canonical \
             space to adopt them into; a governed transition must establish one first",
            legacy_spaces.len()
        ));
    };

    let vault = crate::commands::server::build_material_vault(
        config,
        &config
            .provider_execution
            .roots()
            .map_err(|_| anyhow!("provider execution storage roots are unavailable or overlap"))?,
    )?;
    let repository = Arc::new(PgEmbeddingLegacyAdoptionRepository::new(store.clone()));
    let service = EmbeddingLegacyAdoptionService::new(
        repository.clone(),
        Arc::new(PgGovernedContentMaterializer::new(
            store.clone(),
            vault.clone(),
            Arc::new(ContentMaterialCodec::new()),
        )),
        Arc::new(PgGovernedEmbeddingJobFactory::new(
            store.clone(),
            Arc::new(PgEmbeddingJobRepository::new(store.clone())),
            Arc::new(PgModelRequestEvidenceRepository::new(vault)),
            EffectiveRequestLimits::new(256, 4, 32_768)
                .map_err(|error| anyhow!("adoption request limits are invalid: {error}"))?,
        )),
        config.embedding.limits.claim_batch,
    )
    .map_err(|error| anyhow!("adoption service composition failed: {error}"))?;

    let mut planned = 0usize;
    for legacy in legacy_spaces {
        let progress = service
            .start_or_resume(
                context,
                StartLegacyAdoption {
                    plan_id: LegacyAdoptionId::new(),
                    legacy_space_registration_id: legacy,
                    target_space_registration_id: canonical,
                    // One plan per legacy space, forever: a second key against
                    // the same space is refused by the database rather than
                    // opening a second plan for the same rows.
                    idempotency_key: format!("rebuild-embeddings:{legacy}"),
                },
            )
            .await
            .with_context(|| format!("legacy adoption for space {legacy} could not start"))?;
        println!();
        println!(
            "  space {legacy}: plan {} is {}, {} member(s), {} satisfied, {} blocked",
            progress.plan_id.as_uuid(),
            progress.state.as_str(),
            progress.total_members,
            progress.satisfied_members,
            progress.blocked_members
        );
        for blocker in &progress.blockers {
            println!(
                "    blocked: member {} -- {}",
                blocker.ordinal,
                blocker.reason.as_str()
            );
        }
        planned += progress.total_members as usize;
    }
    println!();
    println!("  the worker recomputes these vectors; this command created no vector itself");
    Ok(planned)
}

/// Every legacy space still registered in this workspace.
async fn legacy_space_registrations(
    store: &PgStore,
    context: &RequestContext,
) -> anyhow::Result<Vec<uuid::Uuid>> {
    let mut scoped = store
        .begin_scoped(context)
        .await
        .context("legacy space registrations are unreadable")?;
    let rows: Vec<(uuid::Uuid,)> = sqlx::query_as(
        "SELECT id FROM embedding_space_registrations \
          WHERE workspace_id = $1 AND registration_kind = 'legacy_upgrade' ORDER BY id",
    )
    .bind(context.workspace_id.as_uuid())
    .fetch_all(scoped.connection())
    .await
    .context("legacy space registrations are unreadable")?;
    scoped.commit().await.ok();
    Ok(rows.into_iter().map(|row| row.0).collect())
}

/// The canonical space retrieval currently answers from, if any.
///
/// Read from the qualification head rather than chosen here: adopting into a
/// space the head does not name would produce a corpus nothing queries.
async fn active_canonical_registration(
    store: &PgStore,
    context: &RequestContext,
) -> anyhow::Result<Option<uuid::Uuid>> {
    let mut scoped = store
        .begin_scoped(context)
        .await
        .context("the qualification head is unreadable")?;
    let row: Option<(uuid::Uuid,)> = sqlx::query_as(
        "SELECT head.active_space_registration_id \
           FROM model_qualification_heads AS head \
           JOIN embedding_space_registrations AS registration \
             ON registration.workspace_id = head.workspace_id \
            AND registration.id = head.active_space_registration_id \
          WHERE head.workspace_id = $1 \
            AND head.active_space_registration_id IS NOT NULL \
            AND registration.registration_kind = 'canonical' \
          ORDER BY head.version DESC LIMIT 1",
    )
    .bind(context.workspace_id.as_uuid())
    .fetch_optional(scoped.connection())
    .await
    .context("the qualification head is unreadable")?;
    scoped.commit().await.ok();
    Ok(row.map(|row| row.0))
}
