#!/usr/bin/env python3
"""Render documentation views from their JSON sources. No product execution.
Run with --check to report drift without writing files. Python 3.10+.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path

GROUPS = {
    'P0': ('p0-foundation.md', 'Foundation and trust blockers', 'Close the production paths and data-preservation guarantees used by a feature before expanding public claims.'),
    'P1': ('p1-memory-workspace.md', 'Governed project memory', 'Deliver the selected read → correct → import → synchronize → transfer workflow.'),
    'P2': ('p2-knowledge-quality.md', 'Knowledge quality and integration', 'Improve usefulness and explanations on measured tasks rather than adding autonomy without evidence.'),
    'P3': ('p3-full-platform.md', 'The approved full-v1.0 platform', 'Product prioritization does not remove any frozen-v1 obligation. These packages remain required for full v1.0.'),
    'P4': ('p4-expansion.md', 'Expansion after external validation', 'Start independent expansions only when demand and operational readiness justify their support cost.'),
}

def render_roadmap(register: dict) -> dict[str, str]:
    locations = {f['id']: GROUPS[f['priority']][0] for f in register['features']}
    result = {}
    for priority, (filename, title, rationale) in GROUPS.items():
        parts = [f'# {priority} — {title}\n',
                 '<!-- Generated by docs/maintenance/render_catalogs.py; edit feature-register.json. -->\n',
                 '**Status:** Proposed priorities. All feature verification remains `NOT_RUN_HERE`.\n',
                 rationale + '\n',
                 'Original source-observation labels retain their historical meaning. See [current status](../status.md) '
                 'for later evidence, including Task 14E. Dependencies describe full acceptance, not a ban on earlier '
                 'read-only design work. Product priorities P0–P4 are not package numbers P01–P12.\n']
        for f in register['features']:
            if f['priority'] != priority:
                continue
            parts += [f'<a id="{f["id"].lower()}"></a>\n', f'## {f["id"]}. {f["title"]}\n',
                      f'**Value:** {f["value"]}\n', f'**Original observation:** `{f["implementation_observation"]}`.\n',
                      f'**Reuse:** {f["reuse"]}\n', '### Deliverables\n']
            parts += [f'{i}. {v}' for i, v in enumerate(f['deliverables'], 1)]
            parts += ['\n### Acceptance\n']
            parts += [f'- **{f["id"]}-AC{i:02d}:** {v}' for i, v in enumerate(f['acceptance'], 1)]
            deps = ', '.join(f'[{d}]({locations[d]}#{d.lower()})' for d in f['depends_on']) or 'No feature predecessor; source/scope preflight is still required'
            packages = ', '.join(f['existing_packages']) or 'No existing package assigned'
            sources = ', '.join(f'[{s}](../maintenance/sources.md#{s.lower()})' for s in f['source_ids'])
            parts += [f'\n**Dependencies:** {deps}.\n', f'**Programs:** {packages}. **Release relationship:** `{f["release_relationship"]}`. **Milestone:** {f["milestone"]}.\n',
                      f'**Non-goals:** {f["non_goals"]}\n', f'**Sources:** {sources}. Source inspection is not runtime qualification.\n']
        parts += ['[Roadmap](README.md) · [Feature register](feature-register.json) · [Program mapping](program-mapping.md)\n']
        result[f'docs/roadmap/{filename}'] = '\n'.join(parts).rstrip() + '\n'
    return result

def render_routes(catalog: dict) -> str:
    parts = ['# Selected HTTP route inventory\n', '<!-- Generated by docs/maintenance/render_catalogs.py; edit route-catalog.json. -->\n',
             '**Scope:** Selected declarations, not full OpenAPI or proof that every handler works. The inventory source is unchanged from the original reviewed pin in the supplied archive.\n',
             'Existing `/ag-ui/*` entries do not establish the complete pinned AG-UI target in P08. Read the handler, authorization, production composition, and runtime evidence for the operation you use.\n',
             '| Method | Path | Capability / exposure | Risk |', '| --- | --- | --- | --- |']
    parts += [f'| `{x["method"]}` | `{x["path"]}` | `{x["capability"]}` | `{x["risk"]}` |' for x in catalog['items']]
    parts += ['\nAn admission-policy route is declared; do not claim that no such route exists. Its declaration alone does not establish full handler completion. Runtime schemas remain in `schemas/`; the Memory Workspace proposal remains `openapi.proposed.json`.\n',
              '[Machine-readable catalog](route-catalog.json) · [HTTP conventions](http.md) · [Status](../status.md)\n']
    return '\n'.join(parts).rstrip() + '\n'

ACCEPTANCE_INTRO = '''# 09. Executable acceptance and adversarial cases

<!-- Generated by docs/maintenance/render_catalogs.py; edit traceability.json. -->

**Every case is NOT RUN in this documentation work.** JSON validation is not a Vestrace runtime result.
The complete requirement/task mapping is in [traceability.json](traceability.json).

## Evidence rules

Record source/build/configuration and environment identities, the exact command and exit code,
sanitized stdout/stderr, independent read-back, and limitations. Never include secret content.
A callback returning an expected value does not establish retrieval or security behavior.
Use the restricted runtime role; administrative bootstrap prepares the environment only.
SQLx fixtures cannot replace production producers in an end-to-end claim.

Race fixtures use independent connections/processes, controlled barriers, bounded timeouts,
and final read-back. Sleep alone does not prove an interleaving. Actually kill a child process
for process-death tests; an injected exception is a rollback test, not crash evidence.

At minimum, mutation tests disable the business receipt check, revision CAS, one workspace
foreign key/predicate, atomic audit/outbox, manual-override check, and export reauthorization.
Each mutant must make the unchanged behavioral test fail in a disposable copy. Restore exact
source bytes and observe GREEN. An ineffective mutant does not prove a load-bearing guard.

## Scenario catalog
'''

def render_acceptance(trace: dict) -> str:
    parts = [ACCEPTANCE_INTRO]
    for c in trace['acceptance_cases']:
        parts += [f'### {c["id"]}. {c["name"]}\n', f'**Requirement:** `{c["requirement"]}`. **Result:** NOT RUN.\n',
                  f'**Given:** {c["given"].rstrip(".")}.\n', f'**Expected:** {c["then"].rstrip(".")}.\n',
                  f'**Counterexample the test must distinguish:** {c["counterexample"].rstrip(".")}.\n']
    parts += ['''## Complete workflow without test-only shortcuts

The first user creates a collection and preview through UI/API, then applies it through the real
worker. A second authorized user reads and corrects memory. A later CLI source import produces
a conflict; the UI resolves it and displays the exact receipt/history. Export runs through the
worker and protected download, then imports into another permitted collection with new mappings.
A third, denied principal receives uniform refusals. Intermediate process crashes must converge
without additional canonical mutations.

Run embedding and actual model calls only in an authorized environment. If the generation path
is unavailable, mark search BLOCKED and do not accept the whole golden scenario. Preserve partial
read/edit evidence without promoting it into a broad runtime claim.

For A35, also exercise the accepted clarification in [MW-05](plans/05-sync.md): after the stale
resolution fails, refresh detail and resolve using current M while preserving detection-time M0.
''']
    return '\n'.join(parts).rstrip() + '\n'


def render_plans(trace: dict, details: dict, fileplan: dict) -> dict[str, str]:
    expanded = {t['id']: t for t in details['tasks']}
    packages = {}
    for task in trace['tasks']:
        packages.setdefault(task['package'], []).append(task)
    titles = ['Baseline, authority, and executable gates', 'Memory reads and Context API',
              'Atomic corrections and replay', 'Console memory workspace',
              'Source import and production delivery', 'Source synchronization and manual conflicts',
              'Portable knowledge export and import', 'Full-workflow feature qualification']
    dependencies = ['Design acceptance', 'MW-00', 'MW-00, MW-01', 'MW-01, MW-02',
                    'MW-02, MW-03', 'MW-04', 'MW-04, MW-05', 'MW-01–MW-06']
    results = {}
    for index, (package, tasks) in enumerate(packages.items()):
        parts = [f'# {package}. {titles[index]}\n',
                 '<!-- Generated by docs/maintenance/render_catalogs.py; edit traceability.json and task-details.json. -->\n',
                 f'**Status:** Proposed implementation plan. **Dependencies:** {dependencies[index]}.\n',
                 'The [shared scope, task procedure, and exit gate](README.md) apply to every task. '
                 'Read [design](../01-design.md), [transactions](../02-data-and-transactions.md), '
                 '[API](../03-api.md), and [acceptance](../09-acceptance.md). '
                 'These instructions record no runtime results.\n',
                 '## Package file map\n',
                 'Original statuses are relative to the original reviewed baseline. Reread existing paths and check '
                 'new names against the implementation checkout. This map is not blanket write authority.\n',
                 '| Path | Original planning status | Responsibility |', '| --- | --- | --- |']
        for f in fileplan['files']:
            if package in f['packages']:
                parts.append(f'| `{f["path"]}` | `{f["status"]}` | {f["purpose"]} |')
        for task in tasks:
            reqs = [r for r in trace['requirements'] if r['task'] == task['id']]
            cases = list(dict.fromkeys(c for r in reqs for c in r['tests']))
            parts += [f'\n## {task["id"]}. {task["title"]}\n',
                      '**Requirements:** ' + ', '.join(r['id'] for r in reqs) + '.  \n**Acceptance:** ' + ', '.join(cases) + '.\n',
                      '### Exact task files\n']
            parts += [f'- `{f}`' for f in expanded[task['id']]['files']]
            parts += ['\n### Interfaces, implementation, and required observations\n', expanded[task['id']]['details_markdown']+'\n',
                      '### Verification command\n',
                      'Run only after the target/fixture exists. Verify behavioral RED, then GREEN and every linked case '
                      'under the [shared procedure](README.md#shared-task-procedure). These are not results of this documentation edition.\n',
                      '```bash\n' + task['test_command'] + '\n```\n']
        parts += ['## Exit gate\n', 'Apply the [shared exit gate](README.md#shared-exit-gate). Unavailable prerequisites remain '
                  'explicit blockers; a checkbox or document check is not runtime evidence.\n']
        results['docs/implementation/memory-workspace/'+tasks[0]['plan']] = '\n'.join(parts).rstrip()+'\n'
    return results

def generated(root: Path, include_mw: bool = True) -> dict[str, str]:
    values = render_roadmap(json.loads((root/'docs/roadmap/feature-register.json').read_text(encoding='utf-8')))
    values['docs/reference/route-catalog.md'] = render_routes(json.loads((root/'docs/reference/route-catalog.json').read_text(encoding='utf-8')))
    if include_mw:
        values['docs/implementation/memory-workspace/09-acceptance.md'] = render_acceptance(json.loads((root/'docs/implementation/memory-workspace/traceability.json').read_text(encoding='utf-8')))
        mw = root/'docs/implementation/memory-workspace'
        values.update(render_plans(json.loads((mw/'traceability.json').read_text(encoding='utf-8')), json.loads((mw/'task-details.json').read_text(encoding='utf-8')), json.loads((mw/'file-plan.json').read_text(encoding='utf-8'))))
    return values

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--root', type=Path, default=Path(__file__).resolve().parents[2])
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--skip-mw', action='store_true')
    args = ap.parse_args()
    drift = []
    for name, text in generated(args.root, not args.skip_mw).items():
        path = args.root/name
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text:
                drift.append(name)
        else:
            path.write_text(text, encoding='utf-8')
    if drift:
        print('Generated documentation drift:\n' + '\n'.join(drift)); return 1
    print('Generated documentation is current.' if args.check else 'Generated documentation written.'); return 0

if __name__ == '__main__':
    raise SystemExit(main())
