[package]
name = "vestrace-domain"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
chrono.workspace = true
schemars.workspace = true
secrecy.workspace = true
ring.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
static_assertions.workspace = true
thiserror.workspace = true
uuid.workspace = true
zeroize.workspace = true
